version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: stationSki
    volumes:
      - db_vol:/var/lib/mysqldb
    networks:
      - mynetwork

  Universite_app:
    build: .
    image: ghassenmarzouk252/skitest:latest
    restart: unless-stopped
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    networks:
      - mynetwork
networks:
    mynetwork:
volumes:
  db_vol: