version: "3.9"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"

    volumes:
      - db:/var/lib/mysql
  app:
    container_name: stationSki
    image: rihemchagour/backend
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "root",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    volumes:
      - app_data:/app/data
volumes:
  app_data:
  db: